# Copyright 2011 Google Inc.  All rights reserved.
# Author: sameb@google.com (Sam Berlin)
package(
    default_visibility = ["//:src"],
)

java_library(
    name = "jmx",
    srcs = glob(["**/*.java"]),
    deps = [
        "//core/src/com/google/inject",
    ],
)
