# Copyright 2011 Google Inc. All Rights Reserved.
# Author: sameb@google.com (Sam Berlin)

package(
    
    default_testonly = 1,
)

# Note: The struts2 build does not support jakarta.servlet, so it is not in the opensource build.
