# Copyright 2011 Google Inc.  All rights reserved.
# Author: sameb@google.com (Sam Berlin)
package(
    default_visibility = ["//:src"],
)

java_library(
    name = "mini",
    srcs = glob(["**/*.java"]),
    deps = [
        "//core/src/com/google/inject",
        "//third_party/java/jsr330_inject",
    ],
)
